services:
  db:
    image: postgres:15-alpine
    container_name: telemetry-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: telemetry
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # NEW: Redis In-Memory Cache
  redis:
    image: redis:7-alpine
    container_name: telemetry-cache
    restart: always
    ports:
      - "6379:6379"
    # We do not map a volume here. Cache is ephemeral! 
    # If the container dies, it safely repopulates from the DB on the next request.

volumes:
  pgdata: