apiVersion: v1
kind: Service
metadata:
  name: telemetry-api-service
  labels:
    app: telemetry-api
spec:
  type: ClusterIP
  selector:
    app: telemetry-api
  ports:
    # We must explicitly name the port "http" so Prometheus can find it
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP