apiVersion: apps/v1
kind: Deployment
metadata:
  name: telemetry-api
  labels:
    app: telemetry-api
spec:
  # We are declaring we want 2 identical instances of our API running
  replicas: 2
  selector:
    matchLabels:
      app: telemetry-api
  template:
    metadata:
      labels:
        app: telemetry-api
    spec:
      containers:
      - name: api
        # UPDATE THIS LINE to use the newly compiled v1.1 image
        image: telemetry-api:v1.3
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        # Changed from host.docker.internal to K8s internal DNS
        - name: REDIS_URL
          value: "redis-service:6379"
        - name: KAFKA_BROKERS
          value: "host.docker.internal:9092"
        - name: JAEGER_ENDPOINT
          value: "jaeger-service:4318"
