apiVersion: apps/v1
kind: Deployment
metadata:
  name: telemetry-worker
  labels:
    app: telemetry-worker
spec:
  # We deploy 2 workers. Kafka will automatically assign different partitions to each, 
  # load-balancing the message consumption perfectly!
  replicas: 2
  selector:
    matchLabels:
      app: telemetry-worker
  template:
    metadata:
      labels:
        app: telemetry-worker
    spec:
      containers:
      - name: worker
        image: telemetry-worker:v1.2
        imagePullPolicy: Never
        env:
        # Changed from host.docker.internal to K8s internal DNS
        - name: DATABASE_URL
          value: "postgres://admin:secretpassword@postgres-service:5432/telemetry"
        - name: KAFKA_BROKERS
          value: "host.docker.internal:9092"
        - name: JAEGER_ENDPOINT
          value: "jaeger-service:4318"
